Public Interface Procedures
    Function NewRecord()
    Function Save()
    Function EditRecord()
    Sub DeleteRecord()
    Sub lastRecord()
    Sub FirstRecord()
    Sub nextRecord()
    Sub PreviousRecord()
    Function cancel()
    Sub find()
    Sub close()
    Sub FillDefault()
    Sub MenuLockUnlock(ByVal Adding As Boolean, ByVal Editing As Boolean)
    Sub LockUnlockMe()
    Sub print()
    Sub Search()
    Sub Refresh()
End Interface
